---
title: "Shiny Template"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
devtools::install_github("ropensci/rotl")

```
```{r}
devtools::install_github("fmichonneau/phyloch")
devtools::install_github("phylotastic/datelife")
```


```{r}
library(shiny)
library(rphylotastic)
library(datelife)
library(ggplot2)
library(maps)
```

```{r}
usaMap <- map_data("state")
```

```{r}
plotMap <- ggplot(usaMap, aes(x=long, y=lat, group = group)) + geom_polygon(fill="white", color = "black")
```

User interface: Building the web doc 

```{r}
#Need to add title and instructions
ui <- fluidPage(
    column(
        width = 6,
        plotOutput("map", click = "clickMap", width = 430, height = 275)
    )
)
  
```

Instructions for the server
```{r}
server <- function(input,output) {
    output$map <- renderPlot({
        plotMap
    })
} #observeEvent for reactivity? 
```

knitting UI and Server instructions
```{r}
shinyApp(ui = ui, server=server)
```

